### ISSUE TITLE
Unable to register extension "EdiModric\Twig\VersionExtension" after modifying layout

### ISSUE THREAD

**Issue by crevillo** [netgen-layouts/layouts-ezplatform-site#1]
Hello. This is something i'm commenting with Ivo in the slack channel. 

Whenever you modify the pagelayout provided and refresh your home page, i get a error saying 

```
(2/2) LogicExceptionUnable to register extension "EdiModric\Twig\VersionExtension" as extensions have already been initialized.
--
```

This has been reproduced starting from this repo and working with php built in server and also following the instructions to add netgen layouts to a existing installation. 

Steps to reproduce:
- follow instructions at https://docs.netgen.io/projects/layouts/en/latest/getting_started/install_new_ezplatform.html to have the project running
- create a layout and map it to ez location "ez platform"
- go to the front page in the public site
- modify the pagelayout and refresh the page. Error should appear.

**Comment by emodric** [comment]
Hi @crevillo ! It turns out Assetic is the one to blame for this issue. It has some Twig related code that runs when the cache is non existent, making it impossible to add extensions to Twig at runtime.

If I deactivate the Assetic bundle, things work fine. Can you verify?

If this fixes it for you, I will remove Assetic support from this repo, since eZ now works with WebPack instead.

This also explains why I haven't been getting this issue on our Media Site: it doesn't use Assetic since forever :D
